name: Daily-Agent
on:
  workflow_dispatch:

jobs:
  test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install
        run: pip install requests huggingface_hub
      - name: Run
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
        run: python agent_daily.py
